jobs:
  build:
    permissions:
      contents: read
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: Checkout Flyway
      uses: actions/checkout@v3
    - continue-on-error: true
      name: Set up JDK ${{ matrix.java }}
      uses: actions/setup-java@v3
      with:
        cache: maven
        distribution: temurin
        java-version: ${{ matrix.java }}
    - continue-on-error: true
      name: Build with Maven
      run: mvn -B install -e --file pom.xml -pl !flyway-database/flyway-database-mongodb
    strategy:
      fail-fast: false
      matrix:
        java:
        - 17
        os:
        - ubuntu-latest
        - macOS-latest
        - windows-latest
name: Build PRs
on:
  repository_dispatch:
    types: trigger-ga___build-pr.yml
