jobs:
  build:
    permissions:
      contents: read
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: Checkout Flyway
      uses: actions/checkout@v3
    - continue-on-error: true
      name: Set up JDK ${{ matrix.java }}
      uses: actions/setup-java@v3
      with:
        cache: maven
        distribution: temurin
        java-version: ${{ matrix.java }}
    - continue-on-error: true
      name: Build with Maven
      run: mvn -B install -e --file pom.xml  "-Dgithub.os=${{ matrix.os }}" -pl !flyway-database/flyway-database-mongodb
    - continue-on-error: true
      name: Smoke Test with Maven
      run: mvn -B exec:java -e --file pom.xml -pl flyway-commandline "-Dexec.mainClass=org.flywaydb.commandline.Main"
        "-Dexec.args=-url='jdbc:h2:mem:db' info"
    strategy:
      matrix:
        java:
        - 17
        os:
        - ubuntu-latest
        - macOS-latest
        - windows-latest
name: Build Release Tags
on:
  repository_dispatch:
    types: trigger-ga___build-release.yml
